/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/traffic-policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTrafficPolicy"];
        put: operations["updateTrafficPolicy"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dns/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDnsProfile"];
        put: operations["updateDnsProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSubscriptions"];
        put?: never;
        post: operations["createSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["reorderSubscriptions"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SubscriptionID"];
            };
            cookie?: never;
        };
        get: operations["getSubscription"];
        put?: never;
        post?: never;
        delete: operations["deleteSubscription"];
        options?: never;
        head?: never;
        patch: operations["updateSubscription"];
        trace?: never;
    };
    "/api/v1/subscriptions/{id}/refresh": {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: components["parameters"]["SubscriptionID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/{id}/activate": {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: components["parameters"]["SubscriptionID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["activateSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/{id}/selection": {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: components["parameters"]["SubscriptionID"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["selectNode"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/{id}/nodes/import": {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: components["parameters"]["SubscriptionID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["importSubscriptionNodes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/{id}/nodes/{nodeId}/link": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SubscriptionID"];
                nodeId: string;
            };
            cookie?: never;
        };
        get: operations["getSubscriptionNodeLink"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/{id}/latency": {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: components["parameters"]["SubscriptionID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["testNodeLatency"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listNodePools"];
        put?: never;
        post: operations["createNodePool"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pools/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["reorderNodePools"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pools/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get: operations["getNodePool"];
        put?: never;
        post?: never;
        delete: operations["deleteNodePool"];
        options?: never;
        head?: never;
        patch: operations["updateNodePool"];
        trace?: never;
    };
    "/api/v1/chains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProxyChains"];
        put?: never;
        post: operations["createProxyChain"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chains/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get: operations["getProxyChain"];
        put?: never;
        post?: never;
        delete: operations["deleteProxyChain"];
        options?: never;
        head?: never;
        patch: operations["updateProxyChain"];
        trace?: never;
    };
    "/api/v1/chains/{id}/latency": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["testProxyChainLatency"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProxyChannels"];
        put?: never;
        post: operations["createProxyChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/channels/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get: operations["getProxyChannel"];
        put?: never;
        post?: never;
        delete: operations["deleteProxyChannel"];
        options?: never;
        head?: never;
        patch: operations["updateProxyChannel"];
        trace?: never;
    };
    "/api/v1/channels/certificate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["downloadProxyChannelCertificate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRuntime"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtime/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateRuntimePreferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listLinks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/links/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["clearLinks"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRules"];
        put?: never;
        post: operations["createRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["reorderRules"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteRule"];
        options?: never;
        head?: never;
        patch: operations["updateRule"];
        trace?: never;
    };
    "/api/v1/rule-pools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRulePools"];
        put?: never;
        post: operations["createRulePool"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rule-pools/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["reorderRulePools"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rule-pools/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteRulePool"];
        options?: never;
        head?: never;
        patch: operations["updateRulePool"];
        trace?: never;
    };
    "/api/v1/runtime/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["applyRuntime"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtime/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["stopRuntime"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectivity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listConnectivityTargets"];
        put?: never;
        post: operations["createConnectivityTarget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectivity/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["testAllConnectivity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectivity/diagnostic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["runConnectivityDiagnostic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectivity/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConnectivityTargetID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteConnectivityTarget"];
        options?: never;
        head?: never;
        patch: operations["updateConnectivityTarget"];
        trace?: never;
    };
    "/api/v1/connectivity/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConnectivityTargetID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["testConnectivity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCore"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["updateCore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rollbackCore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ConnectivityTarget: {
            id: string;
            name: string;
            url: string;
        };
        CreateConnectivityTarget: {
            name: string;
            url: string;
        };
        UpdateConnectivityTarget: {
            name?: string;
            url?: string;
        };
        ConnectivityPathResult: {
            /** @enum {string} */
            status: "ok" | "timeout" | "failed";
            latencyMs?: number;
            detail?: string;
        };
        ConnectivityResult: {
            targetId: string;
            name: string;
            url: string;
            direct: components["schemas"]["ConnectivityPathResult"];
            proxy?: components["schemas"]["ConnectivityPathResult"];
        };
        ConnectivityTestResponse: {
            items: components["schemas"]["ConnectivityResult"][];
        };
        ConnectivityDiagnosticInput: {
            /** @enum {string} */
            kind: "quality" | "exit";
            /** @enum {string} */
            provider: 123169 | "ippure" | "ipify" | "ipsb" | "ifconfigme" | "icanhazip" | "ipinfo";
        };
        ConnectivityDiagnosticResult: {
            /** @enum {string} */
            kind: "quality" | "exit";
            provider: string;
            providerName: string;
            /** Format: uri */
            url: string;
            latencyMs: number;
            ip?: string;
            country?: string;
            countryCode?: string;
            region?: string;
            city?: string;
            asn?: string;
            organization?: string;
            fraudScore?: number;
            residential?: boolean;
        };
        Health: {
            /** @constant */
            status: "ok";
        };
        Session: {
            csrfToken: string;
        };
        ComponentStatus: {
            /** @enum {string} */
            state: "healthy" | "unavailable" | "degraded" | "failed";
            detail?: string;
        };
        Status: {
            service: string;
            version: string;
            components: {
                [key: string]: components["schemas"]["ComponentStatus"];
            };
            /** Format: date-time */
            timestamp: string;
        };
        Node: {
            id: string;
            name: string;
            type: string;
            server: string;
            port: number;
            tls: boolean;
            selected: boolean;
        };
        NodeLink: {
            /** @description Credential-bearing proxy URI. Must not be cached or included in list responses. */
            link: string;
            /**
             * @description Whether the URI was preserved from the source or generated from the current node configuration.
             * @enum {string}
             */
            source: "original" | "generated";
        };
        Subscription: {
            id: string;
            name: string;
            url: string;
            autoUpdate: boolean;
            updateIntervalMinutes: number;
            active: boolean;
            selectedNodeId?: string;
            /** Format: date-time */
            lastUpdated?: string;
            lastError?: string;
            /**
             * @description 上次成功拉取所用的路径（direct 直连 / proxy 代理回退）。
             * @enum {string}
             */
            lastFetchPath?: "direct" | "proxy";
            nodeCount: number;
            nodes?: components["schemas"]["Node"][];
        };
        CreateSubscription: {
            name: string;
            /** Format: uri */
            url: string;
            autoUpdate: boolean;
            updateIntervalMinutes: number;
        };
        UpdateSubscription: {
            name?: string;
            autoUpdate?: boolean;
            updateIntervalMinutes?: number;
        };
        SubscriptionOrder: {
            ids: string[];
        };
        ImportNodesInput: {
            links: string;
        };
        ImportNodeItem: {
            line: number;
            /** @enum {string} */
            status: "added" | "duplicate" | "invalid";
            error?: string;
            node?: components["schemas"]["Node"];
        };
        ImportNodesResponse: {
            addedCount: number;
            duplicateCount: number;
            invalidCount: number;
            items: components["schemas"]["ImportNodeItem"][];
            subscription: components["schemas"]["Subscription"];
        };
        LatencyRequest: {
            nodeIds?: string[];
        };
        RuleCondition: {
            /** @enum {string} */
            type: "domain" | "domain_suffix" | "domain_keyword" | "ip_cidr" | "ip_is_private" | "port" | "port_range" | "process_name" | "network" | "protocol";
            values?: string[];
        };
        Rule: {
            id: string;
            name: string;
            enabled: boolean;
            /** @enum {string} */
            origin: "builtin" | "manual" | "subscription";
            subscriptionId?: string;
            subscriptionName?: string;
            conditions?: components["schemas"]["RuleCondition"][];
            /** @enum {string} */
            action: "proxy" | "direct" | "block";
            supported: boolean;
            unsupportedReason?: string;
            source?: string;
            position: number;
            locked?: boolean;
        };
        CreateRule: {
            name: string;
            enabled: boolean;
            conditions: components["schemas"]["RuleCondition"][];
            /** @enum {string} */
            action: "proxy" | "direct" | "block";
        };
        UpdateRule: {
            name?: string;
            enabled?: boolean;
            conditions?: components["schemas"]["RuleCondition"][];
            /** @enum {string} */
            action?: "proxy" | "direct" | "block";
        };
        RuleOrder: {
            ids: string[];
        };
        PoolRule: {
            id: string;
            name: string;
            enabled: boolean;
            conditions: components["schemas"]["RuleCondition"][];
            /** @enum {string} */
            action: "proxy" | "direct" | "block";
            position: number;
        };
        RulePool: {
            id: string;
            name: string;
            enabled: boolean;
            position: number;
            rules: components["schemas"]["PoolRule"][];
        };
        CreateRulePool: {
            name: string;
            enabled: boolean;
            rules: components["schemas"]["CreateRule"][];
        };
        UpdateRulePool: {
            name?: string;
            enabled?: boolean;
            rules?: components["schemas"]["CreateRule"][];
        };
        RulePoolOrder: {
            ids: string[];
        };
        LatencyResult: {
            nodeId: string;
            name: string;
            /** @description Ordered nodes traversed by a chain test, from entry to exit. */
            path?: string[];
            /** @enum {string} */
            status: "ok" | "timeout" | "failed";
            latencyMs?: number;
            detail?: string;
        };
        LatencyResponse: {
            items: components["schemas"]["LatencyResult"][];
        };
        NodePoolMemberRef: {
            subscriptionId: string;
            nodeId: string;
        };
        NodePoolMember: {
            subscriptionId: string;
            subscriptionName?: string;
            nodeId: string;
            nodeName?: string;
            type?: string;
            server?: string;
            port?: number;
            available: boolean;
        };
        NodePool: {
            id: string;
            name: string;
            members: components["schemas"]["NodePoolMember"][];
            memberCount: number;
            availableCount: number;
            probeIntervalSeconds: number;
            toleranceMs: number;
            /** Format: uri */
            probeUrl: string;
            fallbackProbeUrls: string[];
            idleTimeoutSeconds: number;
            highLatencyThresholdMs: number;
            consecutiveFailures: number;
            recoverySuccesses: number;
            maxBackoffSeconds: number;
            interruptExistingConnections: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        NodePoolOrder: {
            ids: string[];
        };
        CreateNodePool: {
            name: string;
            members: components["schemas"]["NodePoolMemberRef"][];
            probeIntervalSeconds: number;
            toleranceMs: number;
            /** Format: uri */
            probeUrl?: string;
            fallbackProbeUrls?: string[];
            idleTimeoutSeconds?: number;
            highLatencyThresholdMs?: number;
            consecutiveFailures?: number;
            recoverySuccesses?: number;
            maxBackoffSeconds?: number;
            interruptExistingConnections?: boolean;
        };
        UpdateNodePool: {
            name?: string;
            members?: components["schemas"]["NodePoolMemberRef"][];
            probeIntervalSeconds?: number;
            toleranceMs?: number;
            /** Format: uri */
            probeUrl?: string;
            fallbackProbeUrls?: string[];
            idleTimeoutSeconds?: number;
            highLatencyThresholdMs?: number;
            consecutiveFailures?: number;
            recoverySuccesses?: number;
            maxBackoffSeconds?: number;
            interruptExistingConnections?: boolean;
        };
        ProxyChain: {
            id: string;
            name: string;
            /** @enum {string} */
            entryType: "node" | "pool";
            entryNode?: components["schemas"]["NodePoolMemberRef"];
            entryPoolId?: string;
            exitNode: components["schemas"]["NodePoolMemberRef"];
            entryName?: string;
            entryMemberCount?: number;
            exitName?: string;
            available: boolean;
            unavailableReason?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateProxyChain: {
            name: string;
            /** @enum {string} */
            entryType: "node" | "pool";
            entryNode?: components["schemas"]["NodePoolMemberRef"];
            entryPoolId?: string;
            exitNode: components["schemas"]["NodePoolMemberRef"];
        } & (unknown | unknown);
        UpdateProxyChain: {
            name?: string;
            /** @enum {string} */
            entryType?: "node" | "pool";
            entryNode?: components["schemas"]["NodePoolMemberRef"];
            entryPoolId?: string;
            exitNode?: components["schemas"]["NodePoolMemberRef"];
        };
        ProxyChannel: {
            id: string;
            name: string;
            /** @enum {string} */
            protocol: "socks5" | "http" | "https";
            /** @enum {string} */
            direction: "forward" | "reverse";
            port: number;
            username?: string;
            password?: string;
            node: components["schemas"]["NodePoolMemberRef"];
            enabled: boolean;
            nodeName?: string;
            listenAddress: string;
            /** @description Reachable host addresses for client applications; shared channels expose routed LAN addresses instead of the wildcard listener. */
            accessAddresses: string[];
            available: boolean;
            unavailableReason?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateProxyChannel: {
            name: string;
            /** @enum {string} */
            protocol: "socks5" | "http" | "https";
            /** @enum {string} */
            direction: "forward" | "reverse";
            port: number;
            username?: string;
            password?: string;
            node: components["schemas"]["NodePoolMemberRef"];
            enabled: boolean;
        };
        UpdateProxyChannel: {
            name?: string;
            /** @enum {string} */
            protocol?: "socks5" | "http" | "https";
            /** @enum {string} */
            direction?: "forward" | "reverse";
            port?: number;
            username?: string;
            password?: string;
            node?: components["schemas"]["NodePoolMemberRef"];
            enabled?: boolean;
        };
        Capability: {
            available: boolean;
            detail: string;
        };
        Capabilities: {
            singBox: components["schemas"]["Capability"];
            systemProxy: components["schemas"]["Capability"];
            tun: components["schemas"]["Capability"];
        };
        PoolHealthMember: {
            subscriptionId: string;
            nodeId: string;
            name: string;
            /** @enum {string} */
            status: "unknown" | "healthy" | "degraded" | "quarantined";
            latencyMs?: number;
            passedTests: number;
            totalTests: number;
            failures: number;
            /** Format: date-time */
            lastCheckedAt?: string;
            /** Format: date-time */
            nextProbeAt?: string;
        };
        PoolHealth: {
            /** @enum {string} */
            state: "unknown" | "healthy" | "degraded" | "outage";
            selectedNodeId?: string;
            selectedName?: string;
            healthyCount: number;
            degradedCount: number;
            members: components["schemas"]["PoolHealthMember"][];
            /** Format: date-time */
            lastCheckedAt?: string;
            lastError?: string;
            idle: boolean;
            /** Format: int64 */
            uploadTotal: number;
            /** Format: int64 */
            downloadTotal: number;
            connections: number;
            /** Format: date-time */
            trafficAt?: string;
        };
        TrafficPolicyEvent: {
            /** Format: date-time */
            timestamp: string;
            type: string;
            message: string;
        };
        TrafficPolicy: {
            enabled: boolean;
            downloadPoolId: string;
            /** Format: int64 */
            triggerRateBytesPerSecond: number;
            triggerDurationSeconds: number;
            /** Format: int64 */
            releaseRateBytesPerSecond: number;
            releaseDurationSeconds: number;
            cooldownSeconds: number;
            /** @enum {string} */
            state: "disabled" | "waiting" | "monitoring" | "triggering" | "active" | "recovering" | "cooldown" | "error";
            /** Format: int64 */
            currentDownloadBps: number;
            activeConnections: number;
            triggerProgressSeconds: number;
            releaseProgressSeconds: number;
            originalPoolId?: string;
            originalPoolName?: string;
            /** Format: date-time */
            activatedAt?: string;
            /** Format: date-time */
            cooldownUntil?: string;
            lastError?: string;
            events: components["schemas"]["TrafficPolicyEvent"][];
        };
        UpdateTrafficPolicy: {
            enabled: boolean;
            downloadPoolId: string;
            /** Format: int64 */
            triggerRateBytesPerSecond: number;
            triggerDurationSeconds: number;
            /** Format: int64 */
            releaseRateBytesPerSecond: number;
            releaseDurationSeconds: number;
            cooldownSeconds: number;
        };
        DnsServer: {
            /** @description Unique 1-32 character identifier; lowercase letters, digits, '-' or '_'. */
            tag: string;
            /** @enum {string} */
            type: "udp" | "tcp" | "tls" | "https" | "quic" | "h3" | "local" | "hosts";
            /** @description IP address or domain of the upstream. Must be empty for local/hosts types. */
            server?: string;
            /** @description Override the default port for the server type. */
            port?: number;
        };
        DnsFakeIP: {
            enabled: boolean;
            /** @description IPv4 CIDR handed out by the fake-ip responder. Defaults to 198.18.0.0/15. */
            inet4Range?: string;
            /** @description IPv6 CIDR handed out by the fake-ip responder. Defaults to fc00::/18. */
            inet6Range?: string;
        };
        DnsProfile: {
            servers: components["schemas"]["DnsServer"][];
            /** @description Tag of the server that answers queries matched by no rule. */
            final: string;
            /** @enum {string} */
            strategy: "prefer_ipv4" | "prefer_ipv6" | "ipv4_only" | "ipv6_only";
            fakeIP: components["schemas"]["DnsFakeIP"];
        };
        UpdateDnsProfile: {
            servers: components["schemas"]["DnsServer"][];
            /** @description Tag of the fallback server. May be empty when exactly one server is configured. */
            final: string;
            /** @enum {string} */
            strategy: "prefer_ipv4" | "prefer_ipv6" | "ipv4_only" | "ipv6_only";
            fakeIP: components["schemas"]["DnsFakeIP"];
        };
        Runtime: {
            /** @enum {string} */
            state: "stopped" | "starting" | "running" | "stopping" | "failed";
            /** @enum {string} */
            mode?: "system-proxy" | "tun";
            /** @enum {string} */
            targetType?: "node" | "pool" | "chain";
            subscriptionId?: string;
            nodeId?: string;
            nodeName?: string;
            poolId?: string;
            poolName?: string;
            chainId?: string;
            chainName?: string;
            /** @enum {string} */
            chainEntryType?: "node" | "pool";
            chainEntryName?: string;
            chainExitName?: string;
            /** @description Whether LAN devices may route through this proxy. */
            allowLan?: boolean;
            /** Format: date-time */
            startedAt?: string;
            lastError?: string;
            capabilities: components["schemas"]["Capabilities"];
            poolHealth?: components["schemas"]["PoolHealth"];
        };
        Link: {
            id: string;
            /** @description Remote host (hostname or IP) with destination port. */
            host: string;
            /** @description Original URL/domain reported by sing-box when available. */
            url?: string;
            network?: string;
            type?: string;
            /** Format: int64 */
            upload: number;
            /** Format: int64 */
            download: number;
            /**
             * Format: double
             * @description Bytes per second, sampled between polls.
             */
            uploadRate: number;
            /**
             * Format: double
             * @description Bytes per second, sampled between polls.
             */
            downloadRate: number;
            /** @description Human-readable node that carried this connection, or direct/block. */
            node: string;
            chain?: string[];
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            firstSeenAt: string;
            /** Format: date-time */
            lastSeenAt: string;
            active: boolean;
        };
        LinkStats: {
            active: number;
            /** @description Number of links returned by the current filter (before pagination). */
            total: number;
            /** Format: int64 */
            uploadTotal: number;
            /** Format: int64 */
            downloadTotal: number;
            /** Format: int64 */
            uploadRate: number;
            /** Format: int64 */
            downloadRate: number;
            /** @description Maximum number of links retained in memory. */
            trackedCapacity: number;
        };
        LinkSnapshot: {
            /** @description Whether connection monitoring is actively polling. */
            running: boolean;
            /** Format: date-time */
            updatedAt: string;
            stats: components["schemas"]["LinkStats"];
            links: components["schemas"]["Link"][];
        };
        ApplyRuntime: {
            subscriptionId?: string;
            nodeId?: string;
            poolId?: string;
            chainId?: string;
            /** @enum {string} */
            mode: "system-proxy" | "tun";
            /**
             * @description Allow other devices on the LAN to route through this proxy.
             * @default false
             */
            allowLan: boolean;
        } & (unknown | unknown | unknown);
        UpdateRuntimePreferences: {
            /** @description Persist LAN access for future proxy starts. */
            allowLan: boolean;
        };
        CoreInfo: {
            /** @enum {string} */
            source: "managed" | "external";
            currentVersion: string;
            previousVersion?: string;
            embeddedVersion: string;
            updateSupported: boolean;
            platform: string;
        };
        CoreUpdate: {
            version?: string;
        };
        ErrorDetail: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
            requestId: string;
        };
    };
    responses: {
        /** @description Structured API error. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        SubscriptionID: string;
        ConnectivityTargetID: string;
        CSRFToken: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Web API process is healthy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current control-plane component status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                };
            };
        };
        responses: {
            /** @description Authentication succeeded and an HttpOnly session cookie was issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The browser session cookie was cleared. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    getTrafficPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Persisted automatic download policy and its current runtime state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrafficPolicy"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateTrafficPolicy: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTrafficPolicy"];
            };
        };
        responses: {
            /** @description Updated policy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrafficPolicy"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getDnsProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Persisted DNS profile used for TUN-mode name resolution. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DnsProfile"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateDnsProfile: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDnsProfile"];
            };
        };
        responses: {
            /** @description Updated DNS profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DnsProfile"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    streamEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent event stream. The first event is a snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Browser session metadata for same-origin mutations. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    listSubscriptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stored subscriptions without credential material. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Subscription"][];
                    };
                };
            };
        };
    };
    createSubscription: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSubscription"];
            };
        };
        responses: {
            /** @description Subscription stored and initial fetch attempted. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    reorderSubscriptions: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscriptionOrder"];
            };
        };
        responses: {
            /** @description Subscriptions in their persisted display order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Subscription"][];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SubscriptionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscription and sanitized node list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteSubscription: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: components["parameters"]["SubscriptionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscription removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    updateSubscription: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: components["parameters"]["SubscriptionID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSubscription"];
            };
        };
        responses: {
            /** @description Updated subscription. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    refreshSubscription: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: components["parameters"]["SubscriptionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Refreshed subscription. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    activateSubscription: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: components["parameters"]["SubscriptionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active subscription changed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    selectNode: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: components["parameters"]["SubscriptionID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    nodeId: string;
                };
            };
        };
        responses: {
            /** @description Selected node changed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    importSubscriptionNodes: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: components["parameters"]["SubscriptionID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportNodesInput"];
            };
        };
        responses: {
            /** @description Per-line import results and the updated subscription. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportNodesResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getSubscriptionNodeLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SubscriptionID"];
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Credential-bearing node URI, returned only on explicit request and never cached. */
            200: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeLink"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    testNodeLatency: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: components["parameters"]["SubscriptionID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LatencyRequest"];
            };
        };
        responses: {
            /** @description End-to-end HTTPS delay results measured through temporary sing-box outbounds. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LatencyResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listNodePools: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stored cross-subscription node pools with live member resolution. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["NodePool"][];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createNodePool: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNodePool"];
            };
        };
        responses: {
            /** @description Node pool created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodePool"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    reorderNodePools: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NodePoolOrder"];
            };
        };
        responses: {
            /** @description Node pools in their persisted display order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["NodePool"][];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getNodePool: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Node pool details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodePool"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteNodePool: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Node pool deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    updateNodePool: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNodePool"];
            };
        };
        responses: {
            /** @description Node pool updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodePool"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listProxyChains: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stored proxy chains with resolved entry and exit status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ProxyChain"][];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createProxyChain: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProxyChain"];
            };
        };
        responses: {
            /** @description Proxy chain created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProxyChain"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getProxyChain: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Proxy chain details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProxyChain"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteProxyChain: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Proxy chain deleted. A running chain must be switched away first. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    updateProxyChain: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProxyChain"];
            };
        };
        responses: {
            /** @description Proxy chain updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProxyChain"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    testProxyChainLatency: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description End-to-end latency for each entry path through the configured exit node. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LatencyResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listProxyChannels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stored proxy channels with resolved node status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ProxyChannel"][];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createProxyChannel: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProxyChannel"];
            };
        };
        responses: {
            /** @description Proxy channel created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProxyChannel"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getProxyChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Proxy channel details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProxyChannel"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteProxyChannel: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Proxy channel deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    updateProxyChannel: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProxyChannel"];
            };
        };
        responses: {
            /** @description Proxy channel updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProxyChannel"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    downloadProxyChannelCertificate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Self-signed CA certificate used by HTTPS proxy channels. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-pem-file": string;
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getRuntime: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current proxy runtime and capabilities. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Runtime"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateRuntimePreferences: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRuntimePreferences"];
            };
        };
        responses: {
            /** @description Persisted runtime preferences and current runtime state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Runtime"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listLinks: {
        parameters: {
            query?: {
                /** @description Case-insensitive substring match across host, URL/domain, node, network, type, and chain. */
                search?: string;
                /** @description Filter to live (true) or closed (false) connections. */
                active?: boolean;
                /** @description Comma-separated sort keys applied in order. Prefix with - for descending. Keys: host, url, node, upload, download, uploadRate, downloadRate, startedAt. Active connections always sort before closed ones. */
                sort?: string;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Snapshot of observed proxy connections. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkSnapshot"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    clearLinks: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connection cache cleared. Monitoring continues. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status: string;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Manual, subscription, and built-in routing rules in evaluation order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Rule"][];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createRule: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRule"];
            };
        };
        responses: {
            /** @description Manual rule created and reloaded when the proxy is running. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    reorderRules: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleOrder"];
            };
        };
        responses: {
            /** @description Manual rules reordered and reloaded when the proxy is running. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Rule"][];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteRule: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Manual rule deleted and reloaded when the proxy is running. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    updateRule: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRule"];
            };
        };
        responses: {
            /** @description Rule updated and reloaded when the proxy is running. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listRulePools: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rule pools in evaluation order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["RulePool"][];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createRulePool: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRulePool"];
            };
        };
        responses: {
            /** @description Rule pool created and reloaded when the proxy is running. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RulePool"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    reorderRulePools: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RulePoolOrder"];
            };
        };
        responses: {
            /** @description Rule pools reordered and reloaded when the proxy is running. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["RulePool"][];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteRulePool: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rule pool deleted and reloaded when the proxy is running. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    updateRulePool: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRulePool"];
            };
        };
        responses: {
            /** @description Rule pool updated atomically and reloaded when the proxy is running. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RulePool"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    applyRuntime: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyRuntime"];
            };
        };
        responses: {
            /** @description Selected node or node pool applied. A running compatible runtime switches its root selector without restarting. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Runtime"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    stopRuntime: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Proxy stopped and system proxy state restored. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Runtime"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listConnectivityTargets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stored quick connectivity test targets. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ConnectivityTarget"][];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createConnectivityTarget: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConnectivityTarget"];
            };
        };
        responses: {
            /** @description Created connectivity target. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectivityTarget"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    testAllConnectivity: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Direct and proxied latency for every stored target, measured concurrently. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectivityTestResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    runConnectivityDiagnostic: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectivityDiagnosticInput"];
            };
        };
        responses: {
            /** @description Quality or exit-IP details measured through the active proxy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectivityDiagnosticResult"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteConnectivityTarget: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: components["parameters"]["ConnectivityTargetID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connectivity target deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    updateConnectivityTarget: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: components["parameters"]["ConnectivityTargetID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateConnectivityTarget"];
            };
        };
        responses: {
            /** @description Updated connectivity target. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectivityTarget"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    testConnectivity: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: components["parameters"]["ConnectivityTargetID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Direct and proxied latency for a single target. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectivityTestResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getCore: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current managed or external sing-box core. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoreInfo"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateCore: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoreUpdate"];
            };
        };
        responses: {
            /** @description Core release installed and activated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoreInfo"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    rollbackCore: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Previous installed core activated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoreInfo"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
