/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/traffic-policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTrafficPolicy"];
        put: operations["updateTrafficPolicy"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSubscriptions"];
        put?: never;
        post: operations["createSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SubscriptionID"];
            };
            cookie?: never;
        };
        get: operations["getSubscription"];
        put?: never;
        post?: never;
        delete: operations["deleteSubscription"];
        options?: never;
        head?: never;
        patch: operations["updateSubscription"];
        trace?: never;
    };
    "/api/v1/subscriptions/{id}/refresh": {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: components["parameters"]["SubscriptionID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/{id}/activate": {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: components["parameters"]["SubscriptionID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["activateSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/{id}/selection": {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: components["parameters"]["SubscriptionID"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["selectNode"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/{id}/latency": {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: components["parameters"]["SubscriptionID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["testNodeLatency"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listNodePools"];
        put?: never;
        post: operations["createNodePool"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pools/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get: operations["getNodePool"];
        put?: never;
        post?: never;
        delete: operations["deleteNodePool"];
        options?: never;
        head?: never;
        patch: operations["updateNodePool"];
        trace?: never;
    };
    "/api/v1/runtime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRuntime"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRules"];
        put?: never;
        post: operations["createRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["reorderRules"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteRule"];
        options?: never;
        head?: never;
        patch: operations["updateRule"];
        trace?: never;
    };
    "/api/v1/rule-pools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRulePools"];
        put?: never;
        post: operations["createRulePool"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rule-pools/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["reorderRulePools"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rule-pools/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteRulePool"];
        options?: never;
        head?: never;
        patch: operations["updateRulePool"];
        trace?: never;
    };
    "/api/v1/runtime/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["applyRuntime"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtime/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["stopRuntime"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCore"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["updateCore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rollbackCore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @constant */
            status: "ok";
        };
        Session: {
            csrfToken: string;
        };
        ComponentStatus: {
            /** @enum {string} */
            state: "healthy" | "unavailable" | "degraded" | "failed";
            detail?: string;
        };
        Status: {
            service: string;
            version: string;
            components: {
                [key: string]: components["schemas"]["ComponentStatus"];
            };
            /** Format: date-time */
            timestamp: string;
        };
        Node: {
            id: string;
            name: string;
            type: string;
            server: string;
            port: number;
            tls: boolean;
            selected: boolean;
        };
        Subscription: {
            id: string;
            name: string;
            url: string;
            autoUpdate: boolean;
            updateIntervalMinutes: number;
            active: boolean;
            selectedNodeId?: string;
            /** Format: date-time */
            lastUpdated?: string;
            lastError?: string;
            nodeCount: number;
            nodes?: components["schemas"]["Node"][];
        };
        CreateSubscription: {
            name: string;
            /** Format: uri */
            url: string;
            autoUpdate: boolean;
            updateIntervalMinutes: number;
        };
        UpdateSubscription: {
            name?: string;
            autoUpdate?: boolean;
            updateIntervalMinutes?: number;
        };
        LatencyRequest: {
            nodeIds?: string[];
        };
        RuleCondition: {
            /** @enum {string} */
            type: "domain" | "domain_suffix" | "domain_keyword" | "ip_cidr" | "ip_is_private" | "port" | "port_range" | "process_name" | "network" | "protocol";
            values?: string[];
        };
        Rule: {
            id: string;
            name: string;
            enabled: boolean;
            /** @enum {string} */
            origin: "builtin" | "manual" | "subscription";
            subscriptionId?: string;
            subscriptionName?: string;
            conditions?: components["schemas"]["RuleCondition"][];
            /** @enum {string} */
            action: "proxy" | "direct" | "block";
            supported: boolean;
            unsupportedReason?: string;
            source?: string;
            position: number;
            locked?: boolean;
        };
        CreateRule: {
            name: string;
            enabled: boolean;
            conditions: components["schemas"]["RuleCondition"][];
            /** @enum {string} */
            action: "proxy" | "direct" | "block";
        };
        UpdateRule: {
            name?: string;
            enabled?: boolean;
            conditions?: components["schemas"]["RuleCondition"][];
            /** @enum {string} */
            action?: "proxy" | "direct" | "block";
        };
        RuleOrder: {
            ids: string[];
        };
        PoolRule: {
            id: string;
            name: string;
            enabled: boolean;
            conditions: components["schemas"]["RuleCondition"][];
            /** @enum {string} */
            action: "proxy" | "direct" | "block";
            position: number;
        };
        RulePool: {
            id: string;
            name: string;
            enabled: boolean;
            position: number;
            rules: components["schemas"]["PoolRule"][];
        };
        CreateRulePool: {
            name: string;
            enabled: boolean;
            rules: components["schemas"]["CreateRule"][];
        };
        UpdateRulePool: {
            name?: string;
            enabled?: boolean;
            rules?: components["schemas"]["CreateRule"][];
        };
        RulePoolOrder: {
            ids: string[];
        };
        LatencyResult: {
            nodeId: string;
            name: string;
            /** @enum {string} */
            status: "ok" | "timeout" | "failed";
            latencyMs?: number;
            detail?: string;
        };
        LatencyResponse: {
            items: components["schemas"]["LatencyResult"][];
        };
        NodePoolMemberRef: {
            subscriptionId: string;
            nodeId: string;
        };
        NodePoolMember: {
            subscriptionId: string;
            subscriptionName?: string;
            nodeId: string;
            nodeName?: string;
            type?: string;
            server?: string;
            port?: number;
            available: boolean;
        };
        NodePool: {
            id: string;
            name: string;
            members: components["schemas"]["NodePoolMember"][];
            memberCount: number;
            availableCount: number;
            probeIntervalSeconds: number;
            toleranceMs: number;
            /** Format: uri */
            probeUrl: string;
            fallbackProbeUrls: string[];
            idleTimeoutSeconds: number;
            highLatencyThresholdMs: number;
            consecutiveFailures: number;
            recoverySuccesses: number;
            maxBackoffSeconds: number;
            interruptExistingConnections: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateNodePool: {
            name: string;
            members: components["schemas"]["NodePoolMemberRef"][];
            probeIntervalSeconds: number;
            toleranceMs: number;
            /** Format: uri */
            probeUrl?: string;
            fallbackProbeUrls?: string[];
            idleTimeoutSeconds?: number;
            highLatencyThresholdMs?: number;
            consecutiveFailures?: number;
            recoverySuccesses?: number;
            maxBackoffSeconds?: number;
            interruptExistingConnections?: boolean;
        };
        UpdateNodePool: {
            name?: string;
            members?: components["schemas"]["NodePoolMemberRef"][];
            probeIntervalSeconds?: number;
            toleranceMs?: number;
            /** Format: uri */
            probeUrl?: string;
            fallbackProbeUrls?: string[];
            idleTimeoutSeconds?: number;
            highLatencyThresholdMs?: number;
            consecutiveFailures?: number;
            recoverySuccesses?: number;
            maxBackoffSeconds?: number;
            interruptExistingConnections?: boolean;
        };
        Capability: {
            available: boolean;
            detail: string;
        };
        Capabilities: {
            singBox: components["schemas"]["Capability"];
            systemProxy: components["schemas"]["Capability"];
            tun: components["schemas"]["Capability"];
        };
        PoolHealthMember: {
            subscriptionId: string;
            nodeId: string;
            name: string;
            /** @enum {string} */
            status: "unknown" | "healthy" | "degraded" | "quarantined";
            latencyMs?: number;
            failures: number;
            /** Format: date-time */
            lastCheckedAt?: string;
            /** Format: date-time */
            nextProbeAt?: string;
        };
        PoolHealth: {
            /** @enum {string} */
            state: "unknown" | "healthy" | "degraded" | "outage";
            selectedNodeId?: string;
            selectedName?: string;
            healthyCount: number;
            degradedCount: number;
            members: components["schemas"]["PoolHealthMember"][];
            /** Format: date-time */
            lastCheckedAt?: string;
            lastError?: string;
            idle: boolean;
            /** Format: int64 */
            uploadTotal: number;
            /** Format: int64 */
            downloadTotal: number;
            connections: number;
            /** Format: date-time */
            trafficAt?: string;
        };
        TrafficPolicyEvent: {
            /** Format: date-time */
            timestamp: string;
            type: string;
            message: string;
        };
        TrafficPolicy: {
            enabled: boolean;
            downloadPoolId: string;
            /** Format: int64 */
            triggerRateBytesPerSecond: number;
            triggerDurationSeconds: number;
            /** Format: int64 */
            releaseRateBytesPerSecond: number;
            releaseDurationSeconds: number;
            cooldownSeconds: number;
            /** @enum {string} */
            state: "disabled" | "waiting" | "monitoring" | "triggering" | "active" | "recovering" | "cooldown" | "error";
            /** Format: int64 */
            currentDownloadBps: number;
            activeConnections: number;
            triggerProgressSeconds: number;
            releaseProgressSeconds: number;
            originalPoolId?: string;
            originalPoolName?: string;
            /** Format: date-time */
            activatedAt?: string;
            /** Format: date-time */
            cooldownUntil?: string;
            lastError?: string;
            events: components["schemas"]["TrafficPolicyEvent"][];
        };
        UpdateTrafficPolicy: {
            enabled: boolean;
            downloadPoolId: string;
            /** Format: int64 */
            triggerRateBytesPerSecond: number;
            triggerDurationSeconds: number;
            /** Format: int64 */
            releaseRateBytesPerSecond: number;
            releaseDurationSeconds: number;
            cooldownSeconds: number;
        };
        Runtime: {
            /** @enum {string} */
            state: "stopped" | "starting" | "running" | "stopping" | "failed";
            /** @enum {string} */
            mode?: "system-proxy" | "tun";
            /** @enum {string} */
            targetType?: "node" | "pool";
            subscriptionId?: string;
            nodeId?: string;
            nodeName?: string;
            poolId?: string;
            poolName?: string;
            /** Format: date-time */
            startedAt?: string;
            lastError?: string;
            capabilities: components["schemas"]["Capabilities"];
            poolHealth?: components["schemas"]["PoolHealth"];
        };
        ApplyRuntime: {
            subscriptionId?: string;
            nodeId?: string;
            poolId?: string;
            /** @enum {string} */
            mode: "system-proxy" | "tun";
        } & (unknown | unknown);
        CoreInfo: {
            /** @enum {string} */
            source: "managed" | "external";
            currentVersion: string;
            previousVersion?: string;
            embeddedVersion: string;
            updateSupported: boolean;
            platform: string;
        };
        CoreUpdate: {
            version?: string;
        };
        ErrorDetail: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
            requestId: string;
        };
    };
    responses: {
        /** @description Structured API error. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        SubscriptionID: string;
        CSRFToken: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Web API process is healthy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current control-plane component status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getTrafficPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Persisted automatic download policy and its current runtime state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrafficPolicy"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateTrafficPolicy: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTrafficPolicy"];
            };
        };
        responses: {
            /** @description Updated policy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrafficPolicy"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    streamEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent event stream. The first event is a snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Browser session metadata for same-origin mutations. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    listSubscriptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stored subscriptions without credential material. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Subscription"][];
                    };
                };
            };
        };
    };
    createSubscription: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSubscription"];
            };
        };
        responses: {
            /** @description Subscription stored and initial fetch attempted. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SubscriptionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscription and sanitized node list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteSubscription: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: components["parameters"]["SubscriptionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscription removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    updateSubscription: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: components["parameters"]["SubscriptionID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSubscription"];
            };
        };
        responses: {
            /** @description Updated subscription. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    refreshSubscription: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: components["parameters"]["SubscriptionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Refreshed subscription. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    activateSubscription: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: components["parameters"]["SubscriptionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active subscription changed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    selectNode: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: components["parameters"]["SubscriptionID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    nodeId: string;
                };
            };
        };
        responses: {
            /** @description Selected node changed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    testNodeLatency: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: components["parameters"]["SubscriptionID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LatencyRequest"];
            };
        };
        responses: {
            /** @description End-to-end HTTPS delay results measured through temporary sing-box outbounds. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LatencyResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listNodePools: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stored cross-subscription node pools with live member resolution. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["NodePool"][];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createNodePool: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNodePool"];
            };
        };
        responses: {
            /** @description Node pool created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodePool"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getNodePool: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Node pool details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodePool"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteNodePool: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Node pool deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    updateNodePool: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNodePool"];
            };
        };
        responses: {
            /** @description Node pool updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodePool"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getRuntime: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current proxy runtime and capabilities. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Runtime"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Manual, subscription, and built-in routing rules in evaluation order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Rule"][];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createRule: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRule"];
            };
        };
        responses: {
            /** @description Manual rule created and reloaded when the proxy is running. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    reorderRules: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleOrder"];
            };
        };
        responses: {
            /** @description Manual rules reordered and reloaded when the proxy is running. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Rule"][];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteRule: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Manual rule deleted and reloaded when the proxy is running. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    updateRule: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRule"];
            };
        };
        responses: {
            /** @description Rule updated and reloaded when the proxy is running. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listRulePools: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rule pools in evaluation order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["RulePool"][];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createRulePool: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRulePool"];
            };
        };
        responses: {
            /** @description Rule pool created and reloaded when the proxy is running. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RulePool"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    reorderRulePools: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RulePoolOrder"];
            };
        };
        responses: {
            /** @description Rule pools reordered and reloaded when the proxy is running. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["RulePool"][];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteRulePool: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rule pool deleted and reloaded when the proxy is running. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    updateRulePool: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRulePool"];
            };
        };
        responses: {
            /** @description Rule pool updated atomically and reloaded when the proxy is running. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RulePool"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    applyRuntime: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyRuntime"];
            };
        };
        responses: {
            /** @description Selected node or node pool and proxy mode applied. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Runtime"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    stopRuntime: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Proxy stopped and system proxy state restored. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Runtime"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getCore: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current managed or external sing-box core. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoreInfo"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateCore: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoreUpdate"];
            };
        };
        responses: {
            /** @description Core release installed and activated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoreInfo"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    rollbackCore: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Previous installed core activated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoreInfo"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
